version: '3'
services:
  node:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=tithe.whatdandoes.info
      - LETSENCRYPT_HOST=tithe.whatdandoes.info
      - LETSENCRYPT_EMAIL=daniel@capitolhill.ca
    volumes:
      - .:/home/node
      - /home/node/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - metamask_offering_collector_data:/data/db
networks:
  default:
    external:
      name: nginx-proxy
volumes:
  metamask_offering_collector_data:

